[project]
name = "customer-support-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kuznetsb", email = "kuznetsbog@gmail.com" }
]
requires-python = ">=3.14,<4.0.0"
dependencies = [
    "langchain-community>=0.4.2",
    "langchain-ollama>=1.1.0",
    "langchain-postgres>=0.0.17",
    "langchain-text-splitters>=1.1.2",
    "pydantic-settings>=2.15.0",
    "streamlit>=1.62.0",
]

[project.scripts]
customer-support-ai = "customer_support_ai:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

[tool.pytest.ini_options]
pythonpath = ["app"]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "ruff>=0.16.4",
]
