"""Initial tables definition

Revision ID: fc9ae23a2d99
Revises: 
Create Date: 2026-09-07 16:10:55.980863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc9ae23a2d99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS feedback"))
    op.execute(
        sa.text("CREATE TYPE feedback.feedback_rating AS ENUM ('helpful', 'unhelpful')")
    )
    op.create_table('agent_turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('retrieved_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='feedback'
    )
    op.create_index('ix_agent_turns_created_at', 'agent_turns', ['created_at'], unique=False, schema='feedback')
    op.create_table('agent_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column(
        'rating',
        postgresql.ENUM(
            'helpful',
            'unhelpful',
            name='feedback_rating',
            schema='feedback',
            create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['turn_id'], ['feedback.agent_turns.id'], name='fk_agent_feedback_turn_id_agent_turns', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turn_id', 'session_id', name='uq_agent_feedback_turn_session'),
    schema='feedback'
    )
    op.create_index('ix_agent_feedback_created_at', 'agent_feedback', ['created_at'], unique=False, schema='feedback')
    op.create_index('ix_agent_feedback_rating', 'agent_feedback', ['rating'], unique=False, schema='feedback')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_feedback_rating', table_name='agent_feedback', schema='feedback')
    op.drop_index('ix_agent_feedback_created_at', table_name='agent_feedback', schema='feedback')
    op.drop_table('agent_feedback', schema='feedback')
    op.drop_index('ix_agent_turns_created_at', table_name='agent_turns', schema='feedback')
    op.drop_table('agent_turns', schema='feedback')
    op.execute(sa.text("DROP TYPE IF EXISTS feedback.feedback_rating"))
    op.execute(sa.text("DROP SCHEMA IF EXISTS feedback"))
    # ### end Alembic commands ###
